### ISSUE TITLE
Can't import arrow

### ISSUE THREAD

**Issue by cheshirex** [crsmithdev/arrow#205]
I just installed arrow and tried to import it. I presume this isn't normal. :-)

Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\arrow\__init__.py", line 3, in <module>
    from .arrow import Arrow
  File "C:\Python27\lib\site-packages\arrow\arrow.py", line 16, in <module>
    from arrow import util, locales, parser, formatter
  File "C:\Python27\lib\site-packages\arrow\parser.py", line 17, in <module>
    class DateTimeParser(object):
  File "C:\Python27\lib\site-packages\arrow\parser.py", line 33, in DateTimePars
er
    'MMMM': re.compile('({0})'.format('|'.join(calendar.month_name[1:])), re.IGN
ORECASE),
AttributeError: 'module' object has no attribute 'month_name'
>>>

**Comment by jaredsuttles** [comment]
I'm going to guess you have `calendar.py` in the directory.

```
$ touch calendar.py
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python2.7/site-packages/arrow/__init__.py", line 3, in <module>
    from .arrow import Arrow
  File "/python2.7/site-packages/arrow/arrow.py", line 16, in <module>
    from arrow import util, locales, parser, formatter
  File "/python2.7/site-packages/arrow/parser.py", line 17, in <module>
    class DateTimeParser(object):
  File "/python2.7/site-packages/arrow/parser.py", line 33, in DateTimeParser
    'MMMM': re.compile('({0})'.format('|'.join(calendar.month_name[1:])), re.IGNORECASE),
AttributeError: 'module' object has no attribute 'month_name'
```

Just change the name :)

**Comment by cheshirex** [comment]
Yes, that does seem to be the case. Thanks!
