### ISSUE TITLE
`arrow.get()` throws `TypeError` inconsistently

### ISSUE THREAD

**Issue by wolverdude** [crsmithdev/arrow#215]
I discovered some inconsistent behavior with regard to `ParseError` and `TypeError` when calling `arrow.get()`

So I'm dealing with epoch timestamps:

    >>> arrow.get(1234567890)
    <Arrow [2009-02-13T23:31:30+00:00]>

Then I try to use a millisecond epoch:

    >>> arrow.get(1234567890000)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "arrow/api.py", line 23, in get
        return _factory.get(*args, **kwargs)
      File "arrow/factory.py", line 171, in get
        raise TypeError('Can\'t parse single argument type of \'{0}\''.format(type(arg)))
    TypeError: Can't parse single argument type of '<type 'int'>'

`TypeError`? But `int` _is_ a valid type. One was just successfully parsed.

Alright, what if I try string epochs...

    >>> arrow.get('1234567890')
    <Arrow [2009-02-13T23:31:30+00:00]>
    >>> arrow.get('1234567890000')
    <Arrow [1234-01-01T00:00:00+00:00]>

That's not consistent.

So what if I _try_ to trigger a `TypeError`? Surely passing a `bool` will trigger that...

    >>> arrow.get(True)
    <Arrow [1970-01-01T00:00:01+00:00]>

I question the usefulness of throwing a `TypeError` at all. If you can't parse it, always throw a `ParseError`. It makes it much easier to catch and handle, especially if there are inconsistent criteria for what's a `TypeError` and what's a `ParseError`.

**Comment by andrewelkins** [comment]
Makes sense. Needs a patch.

**Comment by mlew** [comment]
It seems like this is resolved now. All of the exceptions listed above seem to resolve consistently now, and there is a separate thread (issue #238) discussing the merits of `arrow.get(True)`.  I suggest closing this bug.
