### ISSUE TITLE
ImportError on Google App Engine

### ISSUE THREAD

**Issue by tatwell** [crsmithdev/arrow#240]
App Engine disables the `subprocess` module which it appears `arrow` requires:

    ERROR    2015-07-02 14:37:09,248 app.py:1423] Exception on /backend/foo [GET]
    Traceback (most recent call last):
      File "/home/klenwell/projects/foo/lib/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/klenwell/projects/foo/lib/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/klenwell/projects/foo/lib/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/klenwell/projects/foo/lib/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/klenwell/projects/foo/lib/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/klenwell/projects/foo/handlers/backend.py", line 13, in east_coast_time
        today = arrow.utcnow().to('US/Eastern').date()
      File "/home/klenwell/projects/foo/lib/arrow/arrow.py", line 456, in to
        tz = parser.TzinfoParser.parse(tz)
      File "/home/klenwell/projects/foo/lib/arrow/parser.py", line 293, in parse
        tzinfo = tz.gettz(string)
      File "/home/klenwell/projects/foo/lib/dateutil/tz.py", line 968, in gettz
        from dateutil.zoneinfo import gettz
      File "/home/klenwell/projects/foo/lib/dateutil/zoneinfo/__init__.py", line 7, in <module>
        from subprocess import check_call
    ImportError: cannot import name check_call

Any workarounds?

**Comment by andrewelkins** [comment]
I did a bit of searching, and didn't find an easy solution. I'll keep it in the back of mind tonight

**Comment by BrianLichliter** [comment]
Earlier versions of dateutil did not use subprocess. I found this out when updating my dateutil to the latest version and having my GAE app break. Rolling back to the original dateutil I was using worked, not sure if this is something you would want to do though. (for reference version 1.5 is the version that works for me)

**Comment by andrewelkins** [comment]
Let us know if that works; We'll add it to the docs.

**Comment by tatwell** [comment]
I finally had a chance to test solution proposed here and it worked.

In my `requirements.txt` file, I followed suggestion by @BrianLichliter and pegged `python-dateutl` to 1.5:

    arrow
    python-dateutil==1.5

You can see arrow in action on App Engine here:
- https://tatwell-python-demo.appspot.com/arrow/now/US-Pacific

Full source here:
- https://github.com/tatwell/python-demo/releases/tag/arrow-lib

Thanks for the help.

**Comment by brianmhunt** [comment]
Should be fixed in dateutil 2.5.3, per https://github.com/dateutil/dateutil/pull/240
