### ISSUE TITLE
Which timezone formats are supported?

### ISSUE THREAD

**Issue by coryvirok** [crsmithdev/arrow#413]
I see that EST is parsable but PST is not:

```py
import arrow
x = 'Thursday, January 3, 2013 12:59am PST'
dt = arrow.get(x, 'dddd, MMMM D, YYYY h:mma ZZZ')
```

Results in

```
Traceback (most recent call last):
  File "out", line 5, in <module>
    dt = arrow.get(x, 'dddd, MMMM D, YYYY h:mma ZZZ')
  File "/home/vagrant/.pyenv/versions/3.6.0/lib/python3.6/site-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.6.0/lib/python3.6/site-packages/arrow/factory.py", line 198, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/home/vagrant/.pyenv/versions/3.6.0/lib/python3.6/site-packages/arrow/parser.py", line 166, in parse
    self._parse_token(token, value, parts)
  File "/home/vagrant/.pyenv/versions/3.6.0/lib/python3.6/site-packages/arrow/parser.py", line 219, in _parse_token
    parts['tzinfo'] = TzinfoParser.parse(value)
  File "/home/vagrant/.pyenv/versions/3.6.0/lib/python3.6/site-packages/arrow/parser.py", line 326, in parse
    raise ParserError('Could not parse timezone expression "{0}"'.format(string))
arrow.parser.ParserError: Could not parse timezone expression "PST"
```

I see a test which contains a reference to PST but doesn't appear to parse it: https://github.com/crsmithdev/arrow/blob/a20b22b410b52e456580db37b1431119c2ed7df8/tests/arrow_tests.py#L190

**Comment by rautamiekka** [comment]
http://stackoverflow.com/questions/27420478/convert-date-time-from-eu-time-zone-to-pst provides 2 alternative ways.

**Comment by pypingou** [comment]
If possible, you really want to avoid the 3 letters code, they are not unique and two zones can have the same 3 letters code while being rather far appart:
````
('EST', datetime.timedelta(-1, 68400)) ['America/Atikokan', 'America/Cayman', 'America/Jamaica', 'America/Panama']
('EST', datetime.timedelta(0, 36000)) ['Australia/Brisbane', 'Australia/Currie', 'Australia/Hobart', 'Australia/Lindeman', 'Australia/Melbourne', 'Australia/Sydney']
...
('IST', datetime.timedelta(0, 3600)) ['Europe/Dublin']
('IST', datetime.timedelta(0, 19800)) ['Asia/Colombo', 'Asia/Kolkata']
````
(Found this a while back: http://blog.pingoured.fr/index.php?post/2014/07/25/The-Joy-of-timezones )

**Comment by coryvirok** [comment]
Thanks for the info! I'll plan on parsing the date strings I have with one of the workarounds and passing that into arrow.
