### ISSUE TITLE
Parsing a date with '|' in the string gets me TypeError: int() argument must be a string or a number, not 'NoneType' 

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [crsmithdev/arrow#501]
arrow==0.10.0

Running this : 

```python

import arrow
t = arrow.get('Dec 31, 2017 | 2:00 AM', 'MMM DD, YYYY | h:mm A')

```
Gives me this exception:

```
Traceback (most recent call last):
  File "/home/Jake/Desktop/python_scripts/arrow_notepad.py", line 3, in <module>
    t = arrow.get('Dec 31, 2017 | 2:00 AM', 'MMM DD, YYYY | h:mm A')
  File "/usr/local/lib/python2.7/dist-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/arrow/factory.py", line 198, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 166, in parse
    self._parse_token(token, value, parts)
  File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 190, in _parse_token
    parts['hour'] = int(value)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by rhan-mentad** [comment]
Try a newer version of arrow, they recently bumped up the python version. 0.10 is from a year ago

**Comment by ifduyue** [comment]
```python
>>> t = arrow.get('Dec 31, 2017 | 2:00 AM', 'MMM DD, YYYY | h:mm A')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/arrow/local/lib/python2.7/site-packages/arrow/api.py", line 22, in get
    return _factory.get(*args, **kwargs)
  File "/tmp/arrow/local/lib/python2.7/site-packages/arrow/factory.py", line 208, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/tmp/arrow/local/lib/python2.7/site-packages/arrow/parser.py", line 182, in parse
    self._parse_token(token, value, parts)
  File "/tmp/arrow/local/lib/python2.7/site-packages/arrow/parser.py", line 206, in _parse_token
    parts['hour'] = int(value)
TypeError: int() argument must be a string or a number, not 'NoneType'
>>> arrow.__version__
'0.12.0'
```

Same for arrow 0.12.0

**Comment by sgnn7** [comment]
This is an issue with RegEx characters (like `?` and `|`) in the format string not being properly escaped in `_generate_pattern_re`. If I have time I can try to see if I can get a patch for it but pretty much don't use these in the formatting string until that's fixed.

**Comment by sgnn7** [comment]
Opened a PR with a fix for this issue,
