### ISSUE TITLE
week granularity not working

### ISSUE THREAD

**Issue by znat** [crsmithdev/arrow#524]
See error:

```
Traceback (most recent call last):
  File "dates_test.py", line 4, in <module>
    print arrow.get('2018-01-12T00:00:00.000-07:00').humanize(locale='en', granularity='week')
  File "/Users/nathanzylbersztejn/miniconda2/envs/rasa/lib/python2.7/site-packages/arrow/arrow.py", line 805, in humanize
    "second", "minute", "hour", "day", "week", "month" or "year"')
AttributeError: Error. Could not understand your level of granularity. Please select between                 "second", "minute", "hour", "day", "week", "month" or "year"
```

**Comment by krisfremen** [comment]
Nice catch.

Even though it's there in the error message, it doesn't have any code to handle week granularity.

**Comment by krisfremen** [comment]
https://github.com/crsmithdev/arrow/pull/529

Got a pull request to fix this.
