### ISSUE TITLE
`arrow.get` raised wrong exception

### ISSUE THREAD

**Issue by tvytlx** [crsmithdev/arrow#535]
```
In [3]: arrow.get('20171017', ['YYYY.M.D'])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-7623ecb42ca2> in <module>()
----> 1 arrow.get('20171017', ['YYYY.M.D'])
...
--> 269             tzinfo=parts.get('tzinfo'))
    270
    271     def _parse_multiformat(self, string, formats):

ValueError: month must be in 1..12
```
I think it should raise `ParserError `

**Comment by krisfremen** [comment]
which version are you using? ParserError is raised with 0.12.1

```
arrow.get('20171017', ['YYYY.M.D'])
arrow.parser.ParserError: Could not match input to any of ['YYYY.M.D'] on '20171017'
```

**Comment by tvytlx** [comment]
```
In [1]: import arrow

In [2]: arrow.__version__
Out[2]: '0.12.1'

In [3]: arrow.get('20171017', ['YYYY.M.D'])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
...
    267             day=parts.get('day', 1), hour=hour, minute=parts.get('minute', 0),
    268             second=parts.get('second', 0), microsecond=parts.get('microsecond', 0),
--> 269             tzinfo=parts.get('tzinfo'))
    270
    271     def _parse_multiformat(self, string, formats):

ValueError: month must be in 1..12
```
Python version is 3.6.3

**Comment by systemcatch** [comment]
I cannot reproduce this error.
```shell
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.12.1'
>>> arrow.get('20171017', ['YYYY.M.D'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/arrow/arrow/api.py", line 22, in get
    return _factory.get(*args, **kwargs)
  File "/home/chris/arrow/arrow/factory.py", line 208, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/home/chris/arrow/arrow/parser.py", line 171, in parse
    return self._parse_multiformat(string, fmt)
  File "/home/chris/arrow/arrow/parser.py", line 286, in _parse_multiformat
    raise ParserError('Could not match input to any of {0} on \'{1}\''.format(formats, string))
arrow.parser.ParserError: Could not match input to any of ['YYYY.M.D'] on '20171017'
```

However I recognize that ValueError message, it's from the datetime module. Trying to trace the calls I think it's being raised on https://github.com/crsmithdev/arrow/blob/master/arrow/parser.py#L269 but I don't have much idea why different error messages are showing for different people.

Probably need to run a debugger on this, any chance you can do that @tvytlx? I note you're using ipython.

**Comment by tvytlx** [comment]
```
> /Users/xiaotan/.pyenv/versions/3.7.0/envs/brm-api/lib/python3.7/site-packages/arrow/parser.py(172)parse()
-> match = fmt_pattern_re.search(string)
(Pdb) ll
165         def parse(self, string, fmt):
166             breakpoint()
167             if isinstance(fmt, list):
168                 return self._parse_multiformat(string, fmt)
169
170             fmt_tokens, fmt_pattern_re = self._generate_pattern_re(fmt)
171
172  ->         match = fmt_pattern_re.search(string)
173             if match is None:
174                 raise ParserError('Failed to match \'{0}\' when parsing \'{1}\''
175                                   .format(fmt_pattern_re.pattern, string))
176             parts = {}
177             for token in fmt_tokens:
178                 if token == 'Do':
179                     value = match.group('value')
180                 else:
181                     value = match.group(token)
182                 self._parse_token(token, value, parts)
183             return self._build_datetime(parts)
(Pdb) fmt_pattern_re
re.compile('(?P<YYYY>\\d{4}).(?P<M>\\d{1,2}).(?P<D>\\d{1,2})', re.IGNORECASE)
(Pdb) n
> /Users/xiaotan/.pyenv/versions/3.7.0/envs/brm-api/lib/python3.7/site-packages/arrow/parser.py(173)parse()
-> if match is None:
(Pdb) match
<re.Match object; span=(0, 8), match='20171017'>
(Pdb) fmt
'YYYY.M.D'
```

the `fmt_pattern_re` generated from `'YYYY.M.D'` should be `(?P<YYYY>\\d{4})\.(?P<M>\\d)\.(?P<D>\\d)`, but now it is `(?P<YYYY>\\d{4}).(?P<M>\\d{1,2}).(?P<D>\\d{1,2})`, and the `match` is not `None`, so it raised a `ValueError` later instead of a `ParserError` which we expect.

Is there some bug in `_generate_pattern_re` method that causes different behavior among different environment? that was really strange.

**Comment by systemcatch** [comment]
This is what I'm seeing right now.
```shell
> /home/chris/arrow/arrow/parser.py(174)parse()
-> match = fmt_pattern_re.search(string)
(Pdb) l
169  	        if isinstance(fmt, list):
170  	            return self._parse_multiformat(string, fmt)
171  	
172  	        fmt_tokens, fmt_pattern_re = self._generate_pattern_re(fmt)
173  	
174  ->	        match = fmt_pattern_re.search(string)
175  	        if match is None:
176  	            raise ParserError('Failed to match \'{}\' when parsing \'{}\''
177  	                              .format(fmt_pattern_re.pattern, string))
178  	        parts = {}
179  	        for token in fmt_tokens:
(Pdb) fmt_pattern_re
re.compile('(?P<YYYY>\\d{4})\\.(?P<M>\\d{1,2})\\.(?P<D>\\d{1,2})', re.IGNORECASE)
(Pdb) s
> /home/chris/arrow/arrow/parser.py(175)parse()
-> if match is None:
(Pdb) p match
None
```
The unescaped dots in your fmt_pattern_re are causing the match.  Why they aren't escaped I don't know yet. https://github.com/crsmithdev/arrow/blob/master/arrow/parser.py#L131 should escape them.

**Comment by tvytlx** [comment]
dot escape line you referred above was [merged to master](https://github.com/crsmithdev/arrow/commit/3f67c8be2cff3e9f634a31e4a48a2c1bf4e0eaa0) after 0.12.1 https://github.com/crsmithdev/arrow/commit/5a481c02babbbc458db7fe98d3cbaa8ad5dd50c7 
 release, so I can't find it on my 0.12.1 source code...


```
    def _generate_pattern_re(self, fmt):

        # fmt is a string of tokens like 'YYYY-MM-DD'
        # we construct a new string by replacing each
        # token by its pattern:
        # 'YYYY-MM-DD' -> '(?P<YYYY>\d{4})-(?P<MM>\d{2})-(?P<DD>\d{2})'
        tokens = []
        offset = 0

        # Extract the bracketed expressions to be reinserted later.
        escaped_fmt = re.sub(self._ESCAPE_RE, "#", fmt)
        # Any number of S is the same as one.
        escaped_fmt = re.sub('S+', 'S', escaped_fmt)
        escaped_data = re.findall(self._ESCAPE_RE, fmt)

        fmt_pattern = escaped_fmt

        for m in self._FORMAT_RE.finditer(escaped_fmt):
            token = m.group(0)
            try:
                input_re = self._input_re_map[token]
            except KeyError:
                raise ParserError('Unrecognized token \'{0}\''.format(token))
            input_pattern = '(?P<{0}>{1})'.format(token, input_re.pattern)
            tokens.append(token)
            # a pattern doesn't have the same length as the token
            # it replaces! We keep the difference in the offset variable.
            # This works because the string is scanned left-to-right and matches
            # are returned in the order found by finditer.
            fmt_pattern = fmt_pattern[:m.start() + offset] + input_pattern + fmt_pattern[m.end() + offset:]
            offset += len(input_pattern) - (m.end() - m.start())

        final_fmt_pattern = ""
        a = fmt_pattern.split("#")
        b = escaped_data

        # Due to the way Python splits, 'a' will always be longer
        for i in range(len(a)):
            final_fmt_pattern += a[i]
            if i < len(b):
                final_fmt_pattern += b[i][1:-1]

        return tokens, re.compile(final_fmt_pattern, flags=re.IGNORECASE)
```

**Comment by systemcatch** [comment]
Well it's not that then. The way forward is for you to step through _generate_pattern_re line and see what happens, though that uses std lib modules so I don't see what could be different there.

The explanation I'm coming round to is that it's something to do with your environment. Can you give us more details on it?

**Comment by tvytlx** [comment]
this commit https://github.com/crsmithdev/arrow/commit/3f67c8be2cff3e9f634a31e4a48a2c1bf4e0eaa0 not included in the 0.12.1 version, that's way the dot didn't escape, and I think you run the code on master, you should use the pip install version to reproduce

**Comment by systemcatch** [comment]
@tvytlx  Looks like you are right. This issue is fixed on master branch and we're hoping to release 0.13.0 very soon. If you need the fix right now then use https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch to install from github.

```shell
chris@ThinkPad:~$ python3.6 -m venv arrow-testing
chris@ThinkPad:~$ source arrow-testing/bin/activate
(arrow-testing) chris@ThinkPad:~$ pip install arrow
...snipped
(arrow-testing) chris@ThinkPad:~$ python
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.12.1'
>>> arrow.get('20171017', ['YYYY.M.D'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/arrow-testing/lib/python3.6/site-packages/arrow/api.py", line 22, in get
    return _factory.get(*args, **kwargs)
  File "/home/chris/arrow-testing/lib/python3.6/site-packages/arrow/factory.py", line 208, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/home/chris/arrow-testing/lib/python3.6/site-packages/arrow/parser.py", line 168, in parse
    return self._parse_multiformat(string, fmt)
  File "/home/chris/arrow-testing/lib/python3.6/site-packages/arrow/parser.py", line 277, in _parse_multiformat
    _datetime = self.parse(string, fmt)
  File "/home/chris/arrow-testing/lib/python3.6/site-packages/arrow/parser.py", line 183, in parse
    return self._build_datetime(parts)
  File "/home/chris/arrow-testing/lib/python3.6/site-packages/arrow/parser.py", line 269, in _build_datetime
    tzinfo=parts.get('tzinfo'))
ValueError: month must be in 1..12
```

**Comment by tvytlx** [comment]
👌
