### ISSUE TITLE
arrow.get breaks under cProfile

### ISSUE THREAD

**Issue by beaugunderson** [crsmithdev/arrow#547]
This example raises an exception when `broken()` is called:

```python
import arrow

from profilehooks import profile


def working():
    a = arrow.get('2018-10-16T08:00:00-07:00')
    print(a)


@profile
def broken():
    a = arrow.get('2018-10-16T08:00:00-07:00')
    print(a)


if __name__ == '__main__':
    working()
    broken()
```

```
2018-10-16T08:00:00-07:00
Traceback (most recent call last):
  File "repro.py", line 19, in <module>
    broken()
  File "/Users/beau/.envs/home/lib/python3.7/site-packages/profilehooks.py", line 239, in new_fn
    return fp(*args, **kw)
  File "/Users/beau/.envs/home/lib/python3.7/site-packages/profilehooks.py", line 347, in __call__
    return profiler.runcall(self.fn, *args, **kw)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "repro.py", line 14, in broken
    print(a)
  File "/Users/beau/.envs/home/lib/python3.7/site-packages/arrow/arrow.py", line 366, in __str__
    return self._datetime.isoformat()
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
```

If I examine the internal `_datetime` attribute I see this inside `broken()`:

```
In [2]: a._datetime
Out[2]: datetime.datetime(2018, 10, 16, 8, 0, tzinfo=tzoffset(None, 2177280000))
```

And this in `working()`:

```
In [2]: a._datetime
Out[2]: datetime.datetime(2018, 10, 16, 8, 0, tzinfo=tzoffset(None, -25200))
```

**Comment by beaugunderson** [comment]
This is with arrow 0.12.1 on Python 3.7 on macOS Mojave.

**Comment by beaugunderson** [comment]
Traced this all the way through to `dateutil.tz.tzoffset()`, so it is not specific to `arrow`:

```python
from profilehooks import profile

from dateutil import tz


def working():
    value = tz.tzoffset(None, -25200)
    print(value)


@profile
def broken():
    value = tz.tzoffset(None, -25200)
    print(value)


if __name__ == '__main__':
    working()
    broken()
```

Prints:

```
tzoffset(None, -25200)
tzoffset(None, 2177280074)
```

**Comment by beaugunderson** [comment]
And further chased it down to `timedelta`; bug open here: https://bugs.python.org/issue35004
