### ISSUE TITLE
Add support for negative timestamps on Windows (before the epoch)

### ISSUE THREAD

**Issue by jadchaar** [crsmithdev/arrow#675]
Currently, on Windows, you get the following error if you pass a negative timestamp:

```shell
(arrow) C:\Users\Chris>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.get(-15675657)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chris\arrow\lib\site-packages\arrow\api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "C:\Users\Chris\arrow\lib\site-packages\arrow\factory.py", line 155, in get
    return self.type.utcfromtimestamp(arg)
  File "C:\Users\Chris\arrow\lib\site-packages\arrow\arrow.py", line 166, in utcfromtimestamp
    dt = datetime.utcfromtimestamp(timestamp)
OSError: [Errno 22] Invalid argument
```

This occurs on all versions of Arrow on Windows and seems to be due to limitations of the `fromtimestamp` and `utcfromtimestamp` methods in the datetime library on Windows.

This functionality works fine on Linux and MacOS:

```shell
venv ❯ python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> import time
>>> arrow.get(time.time())
<Arrow [2019-09-14T15:41:17.997282+00:00]>
>>> arrow.get(time.time() * -1)
<Arrow [1920-04-19T08:18:37.826506+00:00]>
```

**Comment by jadchaar** [comment]
As discussed in https://github.com/crsmithdev/arrow/issues/668, a possible solution could be to check whether the timestamp is negative and whether the OS is Windows, and based on that, use a purely `timedelta` solution instead:

```python
        if os.name == "nt" and timestamp < 0:
            sec = 0
            microsec = 0
            if isinstance(timestamp, int):
                sec = timestamp
            else:
                whole, frac = str(timestamp).split(".")
                sec = int(whole)
                microsec = int(frac) * -1
            dt = datetime(1970, 1, 1) + timedelta(seconds=sec, microseconds=microsec)
        else:
            dt = datetime.fromtimestamp(timestamp, tzinfo)
```

This code is a bit sloppy and can definitely be cleaned up, but the idea is there.

**Comment by abschmidt6** [comment]
I'm interested in working on this feature, I will take a look at it!

**Comment by jadchaar** [comment]
Hey @abschmidt6, thanks for offering to help on this issue, but we already have an open PR for it here that is almost ready to be merged in: https://github.com/crsmithdev/arrow/pull/700.

**Comment by jadchaar** [comment]
Reopening this issue as the old patch was reverted due to DST issues. Currently, the negative timestamp tests are being ignored on Windows: https://github.com/crsmithdev/arrow/blob/6c74b8c84eded5d50bb97120972322da4586b481/tests/test_parser.py#L243-L257, but it would be nice to support this on Windows through the use of timedeltas (ref: https://stackoverflow.com/q/36179914/)so we have feature parity across OSes.

A potential solution could be to use datetime.fromtimestamp() with a positive version of the timestamp, get the total seconds, and then subtract it from 1970-01-01 as a timedelta.
