### ISSUE TITLE
'datetime.timedelta' object has no attribute 'tzinfo' on windows 10

### ISSUE THREAD

**Issue by Razzeee** [crsmithdev/arrow#738]
## Issue Description

This is a bit specific, but I'm grasping for straws at this point. So I'm using arrow via a kodi script. And it works without problems on linux. A team member tried using my script on windows 10, he get's this stack trace.

```
2019-12-14 10:29:01.961 T:1472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'AttributeError'>
                                            Error Contents: 'datetime.timedelta' object has no attribute 'tzinfo'
                                            Traceback (most recent call last):
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\metadata.tvdb.com.python\scraper.py", line 3, in <module>
                                                from resources.lib import actions
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\metadata.tvdb.com.python\resources\lib\actions.py", line 10, in <module>
                                                from . import series
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\metadata.tvdb.com.python\resources\lib\series.py", line 11, in <module>
                                                from .ratings import ratings
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\metadata.tvdb.com.python\resources\lib\ratings.py", line 6, in <module>
                                                from .trakt_rating import get_trakt_rating_and_votes
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\metadata.tvdb.com.python\resources\lib\trakt_rating.py", line 1, in <module>
                                                from trakt import Trakt
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.trakt\lib\trakt\__init__.py", line 3, in <module>
                                                from trakt.client import TraktClient
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.trakt\lib\trakt\client.py", line 3, in <module>
                                                from trakt.core.configuration import ConfigurationManager
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.trakt\lib\trakt\core\configuration.py", line 3, in <module>
                                                from trakt.core.context_collection import ContextCollection
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.trakt\lib\trakt\core\context_collection.py", line 3, in <module>
                                                from trakt.core.helpers import synchronized
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.trakt\lib\trakt\core\helpers.py", line 9, in <module>
                                                import arrow
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.arrow\lib\arrow\__init__.py", line 3, in <module>
                                                from .api import get, now, utcnow
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.arrow\lib\arrow\api.py", line 10, in <module>
                                                from arrow.factory import ArrowFactory
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.arrow\lib\arrow\factory.py", line 19, in <module>
                                                from arrow.arrow import Arrow
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 1396, in <module>
                                                Arrow.max = Arrow.fromdatetime(datetime.max)
                                              File "C:\KODI\KODI- v19 nightlies\portable_data\addons\script.module.arrow\lib\arrow\arrow.py", line 217, in fromdatetime
                                                if dt.tzinfo is None:
                                            AttributeError: 'datetime.timedelta' object has no attribute 'tzinfo'
                                            -->End of Python script error report<--
```

## System Info

- 🖥 **OS name and version**: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.18362
- 🐍 **Python version**: 3.7 (this might be connected as my linux system is already running 3.8)
- 🏹 **Arrow version**: 0.15.4

**Comment by jadchaar** [comment]
Hmm thanks for reporting this, it seems like a very peculiar bug. It seems like `datetime.max` on Windows is producing a `timedelta` for some reason.

@systemcatch if you have a Windows 10 machine with Python installed, mind checking out the output of the following:

```shell
env ❯ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> from datetime import datetime, timedelta
>>> arrow.Arrow.fromdatetime(datetime.max)
<Arrow [9999-12-31T23:59:59.999999+00:00]>
>>> datetime.max
datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
>>> type(datetime.max)
<class 'datetime.datetime'>
>>> timedelta.max
datetime.timedelta(days=999999999, seconds=86399, microseconds=999999)
>>> type(timedelta.max)
<class 'datetime.timedelta'>
```

@Razzeee do you know what particular set of actions led to this error occurring?

**Comment by Razzeee** [comment]
It seems to happen on import, as the stacktrace shows. I don't think any specific logic is running at that point.

here's a finding from another team member, just to log it, feel free to ignore it:
```
spooky. That Python error is caused by `datetime.max` returning an object of type "bytes" instead of a datetime. I can reproduce it (on Windows). Further testing shows sometimes this happens to `datetime.min`, and sometimes either of them can also return an object of type `datetime.timedelta`. 
```

**Comment by jadchaar** [comment]
Thanks for the details. Is he able to completely reproduce this for both `datetime.min` and `datetime.max`? Or is it **sometimes** the case that it returns `bytes` and **sometimes** the case that it returns a `datetime.timedelta` object? Also are these two different team members?

**Comment by Razzeee** [comment]
It's a different team member, but please keep in mind, that we might deal with a bug in the python version we include in kodi. Which might have patches. 
I ask him for more info on the sometimes stuff.

Also the first team member I mentioned, had no problems with my script some days ago, then it broke. He might have updated to the latest nightly. I'll let him try an older build, just to make sure.

**Comment by systemcatch** [comment]
@jadchaar here's the output you wanted, running on Microsoft Windows 10 Home, Version 10.0.17763 Build 17763

```shell
(arrow) C:\Users\Chris>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import arrow
>>> arrow.__version__
'0.15.4'
>>> from datetime import datetime, timedelta
>>> arrow.Arrow.fromdatetime(datetime.max)
<Arrow [9999-12-31T23:59:59.999999+00:00]>
>>> datetime.max
datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
>>> type(datetime.max)
<class 'datetime.datetime'>
>>> timedelta.max
datetime.timedelta(days=999999999, seconds=86399, microseconds=999999)
>>> type(timedelta.max)
<class 'datetime.timedelta'>
```

**Comment by jadchaar** [comment]
Any updates on this @Razzeee?

**Comment by Razzeee** [comment]
We're investigating, at this point I'm pretty convinced, that it's due to
an implementation bug on our side. The windows guys are still working on it.

You can close this issue for now. Thank you.

**Comment by jadchaar** [comment]
Please keep us updated :). I will close this for now, but please feel free to re-open it if the issue persists so we can investigate further.

**Comment by SoundsSerious** [comment]
Also seeing this bug on windows system linux

**Comment by jadchaar** [comment]
> Also seeing this bug on windows system linux
> 
> Is there a stable version of arrow that doesn't exhibit this behavior?

Could you post some more information on the issue you are seeing? E.g.a snippet of code that is triggering the exception?

**Comment by syd3n** [comment]
I am seeing this error message on Windows when trying to install a Kodi addon/script (one which @Razzeee is a contributor for) - so not sure if it is specific to Arrow or the script itself:

```log
2021-03-09 15:44:33.689 T:23256   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'datetime.timedelta' object has no attribute 'tzinfo'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.trakt\default.py", line 6, in <module>
                                                       from resources.lib.service import traktService
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\service.py", line 20, in <module>
                                                       from resources.lib.traktapi import traktAPI
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\traktapi.py", line 17, in <module>
                                                       from trakt import Trakt
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\__init__.py", line 3, in <module>
                                                       from trakt.client import TraktClient
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\client.py", line 3, in <module>
                                                       from trakt.core.configuration import ConfigurationManager
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\configuration.py", line 3, in <module>
                                                       from trakt.core.context_collection import ContextCollection
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\context_collection.py", line 3, in <module>
                                                       from trakt.core.helpers import synchronized
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\helpers.py", line 9, in <module>
                                                       import arrow
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\__init__.py", line 3, in <module>
                                                       from .api import get, now, utcnow
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\api.py", line 10, in <module>
                                                       from arrow.factory import ArrowFactory
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\factory.py", line 19, in <module>
                                                       from arrow.arrow import Arrow
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\arrow.py", line 1396, in <module>
                                                       Arrow.max = Arrow.fromdatetime(datetime.max)
                                                     File "C:\Users\myusername\AppData\Roaming\Kodi\addons\script.module.arrow\lib\arrow\arrow.py", line 217, in fromdatetime
                                                       if dt.tzinfo is None:
                                                   AttributeError: 'datetime.timedelta' object has no attribute 'tzinfo'
                                                   -->End of Python script error report<--
```

**Comment by systemcatch** [comment]
Hey @syd3n what version of arrow are you using? Try upgrading to the latest release (1.0.3) if possible.

**Comment by syd3n** [comment]
@systemcatch thanks for the response!

Here's the addon script I was installing within Kodi: https://github.com/Razzeee/script.trakt

**Comment by syd3n** [comment]
Actually, I believe it is this one as it has more recent commits: https://github.com/trakt/script.trakt

**Comment by systemcatch** [comment]
Woah `0.10.0` is pretty ancient! :sweat_smile: 

What python versions do you need to support? Latest `1.0.3` is python 3.6+ only but has specific fixes for `datetime.max` on Windows.

**Comment by Razzeee** [comment]
I think 3.8+ would be fine for us. But I think `trakt.py` itself wants to be py2 and py3. Not sure if that's still what they want, as it has been like that for years.

**Comment by systemcatch** [comment]
@Razzeee well in that case `0.17.0` is the last version they could use, still a big improvement over `0.10.0` though!

**Comment by MarkusEh** [comment]
Hi,

I checked in git, and
`        if tzinfo is None:
            if dt.tzinfo is None:
                tzinfo = dateutil_tz.tzutc()
            else:
                tzinfo = dt.tzinfo`
is still part of "https://github.com/arrow-py/arrow/blob/master/arrow/arrow.py".
On my rpi3 system: Kodi (19.4 (19.4.0) Git:20220315-c9de65b422). Platform: Linux ARM 32-bit, 
`2022-04-01 06:00:41.538 T:3290    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'datetime.timedelta' object has no attribute 'tzinfo'
                                                   Traceback (most recent call last):
                                                     File "/var/lib/vdr/.kodi/addons/script.embuary.info/default.py", line 7, in <module>
                                                       from resources.lib.helper import *
                                                     File "/var/lib/vdr/.kodi/addons/script.embuary.info/resources/lib/helper.py", line 15, in <module>
                                                       import arrow
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/arrow.py", line 1704, in <module>
                                                       Arrow.max = Arrow.fromdatetime(dt_datetime.max)
                                                     File "/var/lib/vdr/.kodi/addons/script.module.arrow/lib/arrow/arrow.py", line 318, in fromdatetime
                                                       if dt.tzinfo is None:
                                                   AttributeError: 'datetime.timedelta' object has no attribute 'tzinfo'
                                                   -->End of Python script error report<--`

Same error also have others, see https://github.com/xbmc/xbmc/issues/17311

**Comment by thezoggy** [comment]
still running into this periodically on win10 with kodi's `script.module.arrow` addon

**Comment by thezoggy** [comment]
fix noted here: https://kodi.wiki/view/Python_Problems

**Comment by wesnm** [comment]
> fix noted here: https://kodi.wiki/view/Python_Problems

I don't think that's the fix for the "timedelta" bug. What's happening in this case is that _datetime.datetime.max_ is being corrupted and replaced by a _datetime.timedelta_ object.

One simple workaround is to replace the last two lines of _arrow.py_ as such:

`Arrow.min = Arrow.fromdatetime(dt_datetime.min)`
`Arrow.max = Arrow.fromdatetime(dt_datetime.max)`

with

`Arrow.min = Arrow.fromdatetime(dt_datetime(1, 1, 1, 0, 0))`
`Arrow.max = Arrow.fromdatetime(dt_datetime(9999, 12, 31, 23, 59, 59, 999999))`

Which isn't perfect, but it works in this case and is unlikely to ever be wrong unless datetime objects support dates further into the future or negative years.
